### ISSUE TITLE
Windows host sync'ing fails when lots of hostnames are sync'd

### ISSUE THREAD

**Issue by metcalfc** [oscar-stack/vagrant-hosts#26]
The WinRM command fails when full hostnames are used (output below).

My Vagrant setup is using Oscar and the vms.yaml looks like:

```

---
vms:
  - name: "master"
    box:  "centos-64-x64-vbox4210-nocm"
    hostname: "master.puppetlabs.vm"
    roles: [ "master" ]

<snip>
  - name: "server2008r2a"
    box: "windows-server-2008-r2-x64-v2"
    hostname: "server2008r2a.puppetlabs.vm"
    roles: [ "windows_agent" ]
    forwarded_ports:
      - { guest: 5985, host: 5985 }
      - { guest: 3389, host: 3389 }
```

```
[server2008r2a] Running provisioner: hosts...
An error occurred executing a remote WinRM command.

Shell: powershell
Command: $HostsLocation = "$env:windir\System32\drivers\etc\hosts";
$HostEntry = "127.0.0.1 localhost"
$HostEntry = "127.0.1.1 server2008r2a.puppetlabs.vm"
if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
$HostEntry = "127.0.1.1 server2008r2a"
if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
$HostEntry = "10.20.1.2 master.puppetlabs.vm"
if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
$HostEntry = "10.20.1.2 master"

<snip>

if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
$HostEntry = "10.20.1.11 server2008r2a.puppetlabs.vm"
if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
$HostEntry = "10.20.1.11 server2008r2a"
if (!((gc $HostsLocation) -contains $HostEntry)) { Add-Content -Path $HostsLocation -Value $HostEntry; }
Message: Command execution failed with an exit code of 1
```
