### ISSUE TITLE
Documentation on how to configure add_localhost_hostnames

### ISSUE THREAD

**Issue by razorsedge** [oscar-stack/vagrant-hosts#41]
From [GH-24] [GH-25] Add option to add hostnames for 127.0.1.1
How should I configure oscar since the below snippit does not seem to work?  I have had to hardcode `@add_localhost_hostnames = false` in lib/vagrant-hosts/config.rb line 50 to get the desired results.

```

---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts, autoconfigure: true, add_localhost_hostnames: false}
  # snip
```
